services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'